[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    require-trusted-types-for = "script"
    content-security-policy = "default-src 'self'; script-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; form-action https:; require-trusted-types-for 'script';"
